# Generated by Django 4.2.2 on 2023-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0002_rename_post_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='author',
            new_name='patient',
        ),
    ]
