# Generated by Django 4.2.2 on 2023-06-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0003_rename_author_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_approved',
        ),
    ]
