# Generated by Django 4.2.2 on 2023-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0004_remove_appointment_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doc_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Doc preffered(if any)'),
        ),
    ]
