# Generated by Django 4.2.2 on 2023-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0005_alter_appointment_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('ENT', 'ENT'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Oncologist', 'Oncologist'), ('Ortho', 'Ortho')], max_length=15),
        ),
    ]
