# Generated by Django 4.2.2 on 2023-06-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0008_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chats',
            field=models.TextField(default=''),
        ),
    ]
