# Generated by Django 4.2.2 on 2023-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0010_rename_chats_chats_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
