# Generated by Django 4.2.2 on 2023-06-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0012_alter_appointment_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.ImageField(null=True, upload_to='prescriptions'),
        ),
    ]
