# Generated by Django 4.2.2 on 2023-06-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0014_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.ImageField(default='BITS_ID_2.jpg', upload_to='prescriptions'),
        ),
    ]
