# Generated by Django 4.2.2 on 2023-06-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0015_alter_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.ImageField(blank=True, upload_to='prescriptions'),
        ),
    ]
